name: "Gen Postman Documentation"
description: "Takes an YML input and generates a Postman collection"

inputs:
  yml:
    description: "The YML file to generate the Postman collection"
    required: true
    default: "postman.yml"
  api-key:
    description: "The Postman API key"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "activity"
  color: "orange"
